name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - List directory structure
        run: ls -R  # Debugging - check file structure

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4.3.0
        with:
          dotnet-version: 8.0.x  

      - name: Restore dependencies
        run: |
          if [ -f "Catalog/Catalog.sln" ]; then
            dotnet restore Catalog/Catalog.sln
          elif [ -f "Catalog.sln" ]; then
            dotnet restore Catalog.sln
          else
            echo "Error: Solution file not found!"
            exit 1
          fi

      - name: Build project
        run: dotnet build Catalog.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test Catalog.sln --configuration Release --no-restore --verbosity normal

      - name: Publish application
        run: dotnet publish Catalog.sln --configuration Release --no-restore --output publish/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: publish/
